### ISSUE TITLE
Fix ''firebaseDB' is assigned a value but never used.' issue in server\controllers\games.js

### ISSUE THREAD

**Issue by tsiliopoulos** [CentennialCollege/COMP308-W2017-Lesson11A#15]
[CodeFactor](https://www.codefactor.io/repository/github/centennialcollege/comp308-w2017-lesson11a/overview/master) found an issue: 'firebaseDB' is assigned a value but never used.

It's currently on:
[server\controllers\games.js:8
](https://www.codefactor.io/repository/github/centennialcollege/comp308-w2017-lesson11a/source/master/server/controllers/games.js#L8)Commit d7f1cc4147a6bb73e748495878f074646a8089e5

**Comment by aagavin** [comment]
We may not want to fix this issue as we may need to code later today
